remote_theme: 'dieghernan/jt'


# A. Site Settings
locale          :      # Fallback "en-US"
title           :  # Fallback "repository_name" REV
title_separator :      # Fallback " | "
subtitle        :   


url             : 
baseurl         : 


  
  
search:
  provider: lunr
  maxwords: 300

# Site Author
author:
  name    : TEST
  avatar  : 

# Social Sharing
twitter:
  site               :   #Avoid the @
og_image             : "./assets/img/gallery/david-monje-YwrD58FfX9g-unsplash.jpg"

# Disqus ID

disqus_shortname: chulapa #Your site id : check your address https://{{ disqus.shortname }}.disqus.com/admin/

# Web tracking using Google
gtag_id:    # gtag.js configuration Google Tag ID 
analytics_id:  # analytics.js id. Provided for backward compatibility, better use gtag_id
# B. Navigations

navbar:
  brand:
    title: TEST
    url: 
    img: 
  nav:
  - title: Showcase
    url: /bootstrap
  - title: Second Level
    child:
    - title: Liquid examples
      url:  /liquid
    - title: Demos
      url: /demo
  - title: Another
    child:
    - title: New
      url: /new
    - title: External url
      url: https://www.google.com/
  - title: Github
    url: https://github.com/dieghernan

footer:
  links:
    - label: "RSS"
      icon: "fa-rss"
      url:  https://www.example.com
    - label: "Twitter"
      icon: "fa-twitter"
      # url:
    - label: "Facebook"
      icon: "fa-facebook"
    - label: "GitHub"
      icon: "fa-github"
      # url:
    - label: "Instagram"
      icon: "fa-instagram"
  

# C. Theme Settings
# Code highlighter 
highlight-skin  :      # Fallback "default" #See http://jwarby.github.io/jekyll-pygments-themes for options

# Google Fonts https://fonts.google.com/, add as many as you want
googlefonts:
 - url: https://fonts.googleapis.com/css?family=Muli:200,300,400,700
 - url: https://fonts.googleapis.com/css?family=Oswald:200,300,400,700

  

# Theme and colors
chulapa-skin: 
  highlight   :  # Fallback "default" #See http://jwarby.github.io/jekyll-pygments-themes for options
  theme       :   # Optional predefined skins
  autothemer  :   # Bool: Use autotheming
  vars        :
    font-family-base: Muli
    headings-font-family: Oswald
    primary: "#2f3c48"
    secondary: "#6f7f8c"
    success: "#3e4d59"
    danger: "#cc330d"
    info: "#5c8f94"
    warning: "#6e9fa5"
    light: "#eceeec"
    dark: "#1e2b37"
    enable-rounded: false
    link-color: "mix($primary, #007bff, 70%)"
    hero-chulapa-bg-color: "$primary"
    navbar-chulapa-toggler-color: "rgba(white, 0.4)"
    navbar-chulapa-toggler-border-color: "rgba(white, 0.1)"
    navbar-chulapa-toggler-color-bg: "transparent"
    
#D. Defaults and collections

collections_dir: collections

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      header_type: "base"
      include_on_search: false
  -
    scope:
      path: ""
      type: "demo"
    values:
      layout: "default"
      header_type: "hero"
      show_bottomnavs: true
      show_sociallinks: true
      show_comments:
      include_on_search: true


#Collections
collections:
  demo:
    output: true



# XX. Other settings - no need to modify
# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  blanklines: true

plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-sitemap

# Exclude these files from production site
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor

include:
 - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
 
  
  
